RESPONSE_TYPE_TEXT = "text"
RESPONSE_TYPE_CHOICE = "choice"
RESPONSE_TYPE_SCALE = "scale"
RESPONSE_TYPE_BOOLEAN = "boolean"

# User roles
ROLE_ADMIN = "admin"
ROLE_USER = "user"

# Survey status
SURVEY_STATUS_DRAFT = "draft"
SURVEY_STATUS_ACTIVE = "active"
SURVEY_STATUS_COMPLETED = "completed"
SURVEY_STATUS_ARCHIVED = "archived"

# Chatbot conversation states
CONVERSATION_STATE_GREETING = "greeting"
CONVERSATION_STATE_QUESTIONING = "questioning"
CONVERSATION_STATE_CLARIFYING = "clarifying"
CONVERSATION_STATE_CONCLUDING = "concluding"